### ISSUE TITLE
1.17.22 becoming unusable due to yanked solana-program-runtime dependency

### ISSUE THREAD

**Issue by ttytm** [orca-so/whirlpools#877]
Below a reproduction example that attempts to use an Orca library, which I'm currently unable to utilize because it specifies `solana-program-runtime = "=1.17.22"` as a dependency. This, in turn, requires `solana_rbpf = "=0.8.0"`, which has been yanked from crates.io.

Create a Cargo project, adding the aforementioned Orca library as a single dependency:

```toml
# Cargo.toml
# ...

[dependencies]
whirlpool-replayer = { git = "https://github.com/orca-so/whirlpool-tx-replayer", package = "whirlpool-replayer" }
```

Try to run the project:
```
❯ cargo run
    Updating git repository `https://github.com/orca-so/whirlpool-tx-replayer`
    Updating crates.io index
    Updating git repository `https://github.com/orca-so/whirlpools`
error: failed to select a version for the requirement `solana_rbpf = "=0.8.0"`
  version 0.8.0 is yanked
location searched: crates.io index
required by package `solana-program-runtime v1.17.22`
    ... which satisfies dependency `solana-program-runtime = "=1.17.22"` of pack
age `replay-engine v0.1.7 (https://github.com/orca-so/whirlpool-tx-replayer#ad95
5f63)`
    ... which satisfies git dependency `replay-engine` of package `whirlpool-rep
layer v0.1.7 (https://github.com/orca-so/whirlpool-tx-replayer#ad955f63)`
    ... which satisfies git dependency `whirlpool-replayer` of package `orca_rep
layer v0.1.0 (/home/t/Dev/Kitchensink/crypto/orca_replayer)`
```

---

Of course, adding the problematic dependency directly will also trigger the error. The above example just demonstrates how it affects one of the orca-so repositories.

```toml
[dependencies]
solana-program-runtime = "=1.17.22"
```

```
❯ cargo run
    Updating crates.io index
error: failed to select a version for the requirement `solana_rbpf = "=0.8.0"`
  version 0.8.0 is yanked
location searched: crates.io index
required by package `solana-program-runtime v1.17.22`
    ... which satisfies dependency `solana-program-runtime = "=1.17.22"` of package `orca_replayer v0.1.0 (/home/t/Dev/Kitchensink/cry
pto/orca_replayer)`
```
